CREATE DATABASE GERENCIACONCURSO;
use gerenciaconcurso;
CREATE TABLE CANDIDATO(
	ID INT AUTO_INCREMENT primary key,
	NOME VARCHAR(45) NOT NULL,
	CPF VARCHAR(11) UNIQUE NOT NULL,
	DATA_NASCIMENTO DATE
);

CREATE TABLE AREA (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(45) NOT NULL
);

CREATE TABLE AREA_CANDIDATO(
	ID_CANDIDATO INT,
	ID_area int,
	primary key (ID_CANDIDATO,ID_AREA),
	FOREIGN KEY (ID_CANDIDATO) REFERENCES CANDIDATO(ID),
	FOREIGN KEY (ID_area) REFERENCES AREA(ID)
);

CREATE TABLE INSTITUICAO(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(45) NOT NULL,
	CNPJ VARCHAR(16) UNIQUE NOT NULL
);

CREATE TABLE RESULTADO(
	
);