CREATE DATABASE GERENCIACONCURSO;

CREATE TABLE CANDIDATO(
	ID INT AUTO_INCREMENT primary key,
	NOME VARCHAR(45) NOT NULL,
	CPF VARCHAR(11) UNIQUE NOT NULL,
	DATA_NASCIMENTO DATE
);

CREATE TABLE AREA (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(45) NOT NULL
);

CREATE TABLE AREA_CANDIDATO(
	ID_CANDIDATO INT,
	ID_area int,
	primary key (ID_CANDIDATO,ID_AREA),
	FOREIGN KEY (ID_CANDIDATO) REFERENCES CANDIDATO(ID),
	FOREIGN KEY (ID_area) REFERENCES AREA(ID)
);

CREATE TABLE INSTITUIÇÃO(
    ID INT AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(45) NOT NULL,
	CNPJ VARCHAR(16)UNIQUE NOT NULL
);

CREATE TABLE CONCURSO(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	QTD_VAGAS INT,
	DATA_PROVA DATE,
	ID_INSTITUICAO INT,
	FOREIGN KEY (ID_INSTITUICAO) REFERENCES INSTITUIÇÃO(ID)
);

CREATE TABLE RESULTADO(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	GABARITO VARCHAR(255),
	ID_CONCURSO INT,
	FOREIGN KEY (ID_CONCURSO) REFERENCES CONCURSO(ID)
);

CREATE TABLE AREA_CONCURSO(
	ID_AREA INT,
	ID_CONCURSO INT,
	PRIMARY KEY (ID_AREA, ID_CONCURSO),
	FOREIGN KEY (ID_AREA) REFERENCES AREA(ID),
	FOREIGN KEY (ID_CONCURSO) REFERENCES CONCURSO(ID)
);























